server:
  port: 8499

spring:
  application:
    name: file-service
  datasource:
    name: file
    url: jdbc:mysql://192.168.2.248:3306/hzt_file?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: startup2018
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      query-timeout: 2400
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  redis:
    database: 0
    host: 192.168.2.101
    port: 8300
    password: newpasswd
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
        max-wait: 5000ms
  cache:
    type: REDIS

mybatis-plus:
  mapper-locations: classpath:/mapper/*/*.xml
  typeAliasesPackage: com.hzt.file.*.domain.po
  global-config:
    db-config:
      field-strategy: NOT_EMPTY
      id-type: AUTO
      db-type: MYSQL
      column-like: false
      capital-mode: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

logging:
  config: classpath:config/spring-logback.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@192.168.2.248:8000/eureka